packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalog:
  "@types/node": ^24.12.3
  drizzle-kit: ^0.31.10
  drizzle-orm: ^0.45.2
  dodopayments: 2.48.0
  posthog-js: ^1.418.10
  react-day-picker: ^10.0.1
  sonner: ^2.0.8
  typescript: ^6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: 0.2.7

overrides:
  vite: "catalog:"

allowBuilds:
  core-js: false
  esbuild: true
  lightningcss: true
  sharp: true
  workerd: true
